# Generated by Django 5.1 on 2024-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='scholarship',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
