# Generated by Django 5.1 on 2024-08-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_feestructure_outstandingdues_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstandingdues',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='outstandingdues',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='OutstandingDues',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
