# Generated by Django 5.1 on 2024-08-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0005_feestructure_outstandingdues_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstandingdues',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to='fee_receipts/'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='hosteler',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='OutstandingDues',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
