# Generated by Django 5.1 on 2024-08-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_remove_outstandingdues_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='fee_receipt',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='hosteler',
        ),
        migrations.CreateModel(
            name='HostelFeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_receipt', models.FileField(blank=True, null=True, upload_to='fee_receipts/')),
                ('receipt_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_fee_details', to='smsapp.studentdetails')),
            ],
        ),
    ]
