# Generated by Django 5.1 on 2024-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0007_remove_studentdetails_fee_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='hosteler',
            field=models.BooleanField(default=False),
        ),
    ]
