# Generated by Django 5.1 on 2024-08-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_studentdetails_hosteler'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='fee_receipts/')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.studentdetails')),
            ],
        ),
    ]
