# Generated by Django 5.1.2 on 2024-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0012_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
