# Generated by Django 5.1.2 on 2024-10-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0013_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
