# Generated by Django 5.1 on 2026-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0017_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('On Leave', 'On Leave')], default='Present', max_length=20),
        ),
    ]
